---
title: "state_correlations"
author: "Arushi Saxena"
date: "4/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(reprex)
library(gt)
library(infer)
library(purrr)
library(skimr)
library(broom)
install.packages("ggpubr")
library(ggpubr) #To show correlation coefficient on the plots 
```

```{r} 
# Read in the google search term popularity by state (from 3/11/20 - 3/29/20)

all_searches <- read_csv("raw-data/google_search_geo.csv",col_types = cols())
all_searches
socialdistance_march_F

# Quick data exploration to see distribution of social distancing scores by state
summary(socialdistance_march_F)
socialdistance_march_F %>%
  ggplot(aes(x=average)) + geom_histogram()

#Need to pivot wider the search data so we can join it with social distancing data and do a scatterplot by state 

all_searches2 <- all_searches %>%
  pivot_wider(names_from = term, values_from = search_term_popularity)

# Inner join the social distancing data with the google search data

joined_data <- all_searches2 %>%
  inner_join(socialdistance_march_F, by = c("State" = "state"))

coronavirus <- joined_data %>%
  ggplot(aes(x=average, y=`coronavirus`)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'Coronavirus'") + scale_x_reverse() + geom_smooth(method = "glm", se = FALSE, color = "black") + stat_cor(method="pearson")

covid <- joined_data %>%
  ggplot(aes(x=average, y=`COVID-19`)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'Coronavirus'") + scale_x_reverse() + geom_smooth(method = "glm", se = FALSE, color = "black") + stat_cor(method="pearson")

social_dist <- joined_data %>%
  ggplot(aes(x=average, y=`social distancing`)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'Coronavirus'") + scale_x_reverse() + geom_smooth(method = "glm", se = FALSE, color = "black") + stat_cor(method="pearson")

all_terms <- joined_data %>%
  ggplot(aes(x=average, y=`all_terms`)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'Coronavirus'") + scale_x_reverse() + geom_smooth(method = "glm", se = FALSE, color = "black") + stat_cor(method="pearson")



###### These are the charts with state being colored
joined_data %>%
  ggplot(aes(x=average, y=`COVID-19`,color=State)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'COVID-19'") + scale_x_reverse() + geom_smooth(method = "lm", se = FALSE, color = "black")

joined_data %>%
  ggplot(aes(x=average, y=`social distancing`, color=State)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Search Term Popularity: 'Social Distancing'") + scale_x_reverse() + stat_smooth(method = "lm", se = FALSE, color = "black")

joined_data %>%
  ggplot(aes(x=average, y=all_terms, color=State)) + geom_point() +theme_classic() + theme(axis.text.x = element_text(angle = 45)) + labs(x="Social Distancing Score", y="Avg. Search Popularity of COVID-19-related terms") + scale_x_reverse() + stat_smooth(method = "lm", se = FALSE, color = "black") 
```

